# Generated by Django 5.2.8 on 2025-11-12 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кампании')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Рекламная кампания',
                'verbose_name_plural': 'Рекламные кампании',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='URL изображения')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bannerflow_app.campaign', verbose_name='Кампания')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
