# Generated by Django 5.2.8 on 2025-11-30 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerflow_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
