# Generated by Django 5.2.8 on 2025-11-30 18:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerflow_app', '0002_campaign_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_game_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Версия игры'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_platform',
            field=models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android'), ('Both', 'iOS и Android')], default='Both', max_length=10, verbose_name='Целевая платформа'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bannerflow_app.campaign', verbose_name='Кампания'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.URLField(verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название баннера'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название кампании'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('paused', 'Приостановлена'), ('stopped', 'Остановлена')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
