# Generated by Django 5.2.8 on 2025-11-30 18:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerflow_app', '0003_campaign_end_date_campaign_target_game_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_ab_test',
            field=models.BooleanField(default=False, verbose_name='A/B тест'),
        ),
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название теста')),
                ('audience_segment', models.CharField(max_length=100, verbose_name='Сегмент аудитории')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banners', models.ManyToManyField(to='bannerflow_app.banner', verbose_name='Баннеры для теста')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bannerflow_app.campaign', verbose_name='Кампания')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('impressions', models.IntegerField(default=0, verbose_name='Показы')),
                ('clicks', models.IntegerField(default=0, verbose_name='Клики')),
                ('conversions', models.IntegerField(default=0, verbose_name='Конверсии')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bannerflow_app.campaign', verbose_name='Кампания')),
            ],
            options={
                'verbose_name': 'Статистика кампании',
                'verbose_name_plural': 'Статистика кампаний',
            },
        ),
    ]
