# Generated by Django 5.2.8 on 2025-11-30 20:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerflow_app', '0004_campaign_is_ab_test_abtest_campaignstatistics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='media_file',
            field=models.FileField(default='banners/default_banner.png', help_text='Поддерживаемые форматы: PNG, JPG, MP4', upload_to='banners/%Y/%m/%d/', verbose_name='Медиафайл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='media_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], default='image', max_length=10, verbose_name='Тип медиа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_geolocation',
            field=models.JSONField(default=list, help_text='Список стран/регионов для таргетинга', verbose_name='Геолокация'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бюджет'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('marketer', 'Маркетолог'), ('analyst', 'Аналитик'), ('admin', 'Администратор')], default='marketer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
