# Generated by Django 5.2.8 on 2025-12-01 20:54

import bannerflow_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerflow_app', '0006_alter_banner_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='media_file',
            field=models.FileField(help_text='Поддерживаемые форматы: PNG, JPG, MP4', upload_to='banners/%Y/%m/%d/', validators=[bannerflow_app.models.validate_media_file], verbose_name='Медиафайл'),
        ),
    ]
