# Generated by Django 5.2.8 on 2025-12-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerflow_app', '0007_alter_banner_media_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('template_type', models.CharField(choices=[('score', 'Баннер со счетом'), ('achievement', 'Баннер с достижением'), ('level', 'Баннер с уровнем'), ('custom', 'Пользовательский шаблон')], default='custom', max_length=20, verbose_name='Тип шаблона')),
                ('html_template', models.TextField(help_text='Используйте {{ переменные }} для подстановки', verbose_name='HTML шаблон')),
                ('css_styles', models.TextField(verbose_name='CSS стили')),
                ('javascript', models.TextField(blank=True, help_text='Для интерактивности', verbose_name='JavaScript код')),
                ('width', models.IntegerField(default=300, verbose_name='Ширина (px)')),
                ('height', models.IntegerField(default=250, verbose_name='Высота (px)')),
                ('preview_image', models.ImageField(blank=True, upload_to='templates/previews/', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон баннера',
                'verbose_name_plural': 'Шаблоны баннеров',
            },
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100, verbose_name='Название игры')),
                ('game_type', models.CharField(choices=[('platformer', 'Платформер'), ('rpg', 'RPG'), ('shooter', 'Шутер'), ('strategy', 'Стратегия'), ('custom', 'Другая')], default='custom', max_length=20, verbose_name='Тип игры')),
                ('player_name', models.CharField(max_length=100, verbose_name='Имя игрока')),
                ('score', models.IntegerField(default=0, verbose_name='Счет')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('play_time', models.IntegerField(default=0, verbose_name='Время игры (минуты)')),
                ('achievements', models.JSONField(default=list, verbose_name='Достижения')),
                ('data_file', models.FileField(help_text='JSON или CSV файл', upload_to='game_data/', verbose_name='Файл данных игры')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Данные игры',
                'verbose_name_plural': 'Данные игр',
            },
        ),
        migrations.CreateModel(
            name='GeneratedBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название баннера')),
                ('html_content', models.TextField(verbose_name='HTML содержимое')),
                ('godot_export', models.FileField(blank=True, upload_to='exports/godot/', verbose_name='Экспорт для Godot')),
                ('preview_url', models.URLField(blank=True, verbose_name='URL предпросмотра')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bannerflow_app.gamedata', verbose_name='Данные игры')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bannerflow_app.bannertemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Сгенерированный баннер',
                'verbose_name_plural': 'Сгенерированные баннеры',
            },
        ),
    ]
