# Generated by Django 5.2.8 on 2025-12-22 20:32

import bannerflow_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerflow_app', '0008_bannertemplate_gamedata_generatedbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignstatistics',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='bannertemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gamedata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='generatedbanner',
            options={},
        ),
        migrations.RemoveField(
            model_name='bannertemplate',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='bannertemplate',
            name='template_type',
        ),
        migrations.RemoveField(
            model_name='generatedbanner',
            name='godot_export',
        ),
        migrations.AlterField(
            model_name='banner',
            name='media_file',
            field=models.FileField(help_text='Поддерживаемые форматы: PNG, JPG, MP4, WEBP (макс. 50MB)', upload_to='banners/%Y/%m/%d/', validators=[bannerflow_app.models.validate_media_file], verbose_name='Медиафайл'),
        ),
        migrations.AlterField(
            model_name='bannertemplate',
            name='css_styles',
            field=models.TextField(blank=True, verbose_name='CSS стили'),
        ),
        migrations.AlterField(
            model_name='bannertemplate',
            name='height',
            field=models.IntegerField(default=250, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='bannertemplate',
            name='html_template',
            field=models.TextField(verbose_name='HTML шаблон'),
        ),
        migrations.AlterField(
            model_name='bannertemplate',
            name='javascript',
            field=models.TextField(blank=True, verbose_name='JavaScript код'),
        ),
        migrations.AlterField(
            model_name='bannertemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название шаблона'),
        ),
        migrations.AlterField(
            model_name='bannertemplate',
            name='width',
            field=models.IntegerField(default=300, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Бюджет не может быть отрицательным'), django.core.validators.MaxValueValidator(1000000000, message='Бюджет не может превышать 1 000 000 000')], verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(help_text='Название должно быть уникальным и содержательным', max_length=255, verbose_name='Название кампании'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_geolocation',
            field=models.JSONField(blank=True, default=list, verbose_name='Геолокация'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='data_file',
            field=models.FileField(help_text='JSON или CSV файл (макс. 10MB)', upload_to='game_data/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json', 'csv'])], verbose_name='Файл данных игры'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='generatedbanner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название баннера'),
        ),
        migrations.DeleteModel(
            name='ABTest',
        ),
        migrations.DeleteModel(
            name='CampaignStatistics',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
