# Generated by Django 5.2.8 on 2025-12-22 20:53

import bannerflow_app.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerflow_app', '0009_remove_campaignstatistics_campaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannertemplate',
            options={'verbose_name': 'Шаблон баннера', 'verbose_name_plural': 'Шаблоны баннеров'},
        ),
        migrations.AlterModelOptions(
            name='gamedata',
            options={'verbose_name': 'Данные игры', 'verbose_name_plural': 'Данные игр'},
        ),
        migrations.AlterModelOptions(
            name='generatedbanner',
            options={'verbose_name': 'Сгенерированный баннер', 'verbose_name_plural': 'Сгенерированные баннеры'},
        ),
        migrations.AddField(
            model_name='bannertemplate',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='templates/previews/', verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='bannertemplate',
            name='template_type',
            field=models.CharField(choices=[('score', 'Баннер со счетом'), ('achievement', 'Баннер с достижением'), ('level', 'Баннер с уровнем'), ('custom', 'Пользовательский шаблон')], default='custom', max_length=20, verbose_name='Тип шаблона'),
        ),
        migrations.AddField(
            model_name='generatedbanner',
            name='godot_export',
            field=models.FileField(blank=True, upload_to='exports/godot/', verbose_name='Экспорт для Godot'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='media_file',
            field=models.FileField(help_text='Поддерживаемые форматы: PNG, JPG, MP4', upload_to='banners/%Y/%m/%d/', validators=[bannerflow_app.models.validate_media_file], verbose_name='Медиафайл'),
        ),
        migrations.AlterField(
            model_name='bannertemplate',
            name='css_styles',
            field=models.TextField(verbose_name='CSS стили'),
        ),
        migrations.AlterField(
            model_name='bannertemplate',
            name='height',
            field=models.IntegerField(default=250, verbose_name='Высота (px)'),
        ),
        migrations.AlterField(
            model_name='bannertemplate',
            name='html_template',
            field=models.TextField(help_text='Используйте {{ переменные }} для подстановки', verbose_name='HTML шаблон'),
        ),
        migrations.AlterField(
            model_name='bannertemplate',
            name='javascript',
            field=models.TextField(blank=True, help_text='Для интерактивности', verbose_name='JavaScript код'),
        ),
        migrations.AlterField(
            model_name='bannertemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название шаблона'),
        ),
        migrations.AlterField(
            model_name='bannertemplate',
            name='width',
            field=models.IntegerField(default=300, verbose_name='Ширина (px)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название кампании'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_geolocation',
            field=models.JSONField(default=list, help_text='Список стран/регионов для таргетинга', verbose_name='Геолокация'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='data_file',
            field=models.FileField(help_text='JSON или CSV файл', upload_to='game_data/', verbose_name='Файл данных игры'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='generatedbanner',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название баннера'),
        ),
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название теста')),
                ('audience_segment', models.CharField(max_length=100, verbose_name='Сегмент аудитории')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banners', models.ManyToManyField(to='bannerflow_app.banner', verbose_name='Баннеры для теста')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bannerflow_app.campaign', verbose_name='Кампания')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('impressions', models.IntegerField(default=0, verbose_name='Показы')),
                ('clicks', models.IntegerField(default=0, verbose_name='Клики')),
                ('conversions', models.IntegerField(default=0, verbose_name='Конверсии')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bannerflow_app.campaign', verbose_name='Кампания')),
            ],
            options={
                'verbose_name': 'Статистика кампании',
                'verbose_name_plural': 'Статистика кампаний',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('marketer', 'Маркетолог'), ('analyst', 'Аналитик'), ('admin', 'Администратор')], default='marketer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
