# Generated by Django 5.2.8 on 2025-12-23 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerflow_app', '0010_alter_bannertemplate_options_alter_gamedata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannertemplate',
            name='height',
            field=models.IntegerField(default=250, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1080)], verbose_name='Высота (px)'),
        ),
        migrations.AlterField(
            model_name='bannertemplate',
            name='width',
            field=models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1920)], verbose_name='Ширина (px)'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Счет'),
        ),
    ]
