# Generated by Django 5.2.8 on 2026-06-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerflow_app', '0011_alter_bannertemplate_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannertemplate',
            name='height',
            field=models.IntegerField(default=250, verbose_name='Высота (px)'),
        ),
        migrations.AlterField(
            model_name='bannertemplate',
            name='width',
            field=models.IntegerField(default=300, verbose_name='Ширина (px)'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Счет'),
        ),
    ]
